LOG_FILE_PATH: "./yourfile.xes"
PDF_OUTPUT_PATH: "./report.pdf"

TIMESTAMP_KEY: "time:timestamp"
ACTIVITY_KEY: "concept:name"
USER_KEY: "requester"
STATUS_KEY: "txSuccessful"
GAS_KEY: "gasUsed"
GAS_LIMIT_KEY: "gas"
LONG_TRACE_IDENTIFIER: "ident:piid"

features:
  merge: true
  redundancy: true
  trace_length: true
  sequence: true
  out_of_gas_exception: true

miners:
  alpha_miner: false
  heuristics_miner: false
  inductive_miner: true

Severity_limits:
  heigh: 220
  medium: 70

TIME_THRESHOLD_SECONDS: 60
MAX_SEQUENCE_LENGTH: 5
MAX_SEQ_SUGGESTIONS: 5
PERCENTILE: 99
MAX_LONG_TRACE_SUGGESTIONS: 5
MAX_OUT_OF_GAS_SUGGESTIONS: 5

FALLBACK_USER_FROM_TRACE: true
TRACE_USER_ATTR: "concept:name"



