LOG_FILE_PATH: "./your-file.xes"
PDF_OUTPUT_PATH: "./report.pdf"

TIMESTAMP_KEY: "time:timestamp"
ACTIVITY_KEY: "concept:name"
USER_KEY: "requester"
STATUS_KEY: "status"
GAS_KEY: "gas"
GAS_LIMIT_KEY: "gasLimit"

features:
  merge: true
  redundancy: true
  trace_length: false
  sequence: true
  out_of_gas_exception: false

miners:
  alpha_miner: false
  heuristics_miner: false
  inductive_miner: false

Severity_limits:
  heigh: 3
  medium: 2

TIME_THRESHOLD_SECONDS: 10
MAX_SEQUENCE_LENGTH: 7
MAX_SEQ_SUGGESTIONS: 3
PERCENTILE: 80
MAX_LONG_TRACE_SUGGESTIONS: 5

FALLBACK_USER_FROM_TRACE: false
TRACE_USER_ATTR: "concept:name"



